version: '3'
services:
  nuxt-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "${NGINX_PORT}:3000"
    environment:
      NODE_ENV: "${NODE_ENV}"
      BASE_URL: "${NUXT_PUBLIC_API_BASE}"
    volumes:
      - .:/app
    restart: always